spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ${NAME_EUREKA_SECURITY}
      password: ${PASSWORD_EUREKA_SECURITY}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false